recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('users.urls')),
    path('recipes/', include("recipes.urls")),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView
from .views import home, create_view, about_view, update_recipe, delete_recipe

app_name = 'recipes'

urlpatterns = [
   path('', home, name='home'),
   path('recipes/', RecipeListView.as_view(), name='list'),
   path('recipes/<pk>', RecipeDetailView.as_view(), name='detail'),
   path('create/', create_view, name='create'),
   path('about/', about_view, name='about'),
   path('update/<pk>/', update_recipe, name='update'),
   path('delete/<pk>/', delete_recipe, name='delete')
] 

users/urls.py
from django.urls import path
from .views import profile, signup_view

app_name = 'users'

urlpatterns = [
  path("profile/", profile.as_view(), name="profile"),
  path("signup/", signup_view, name="signup" )
]

users/models.py
from django.db import models
from django.contrib.auth.models import User #needed for OneToOneField

class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name= models.CharField(max_length=120)
    email = models.EmailField(default='example@example.com')
    pic = models.ImageField(upload_to='users', default='no_picture.jpg')
    description= models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.name)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    name = forms.CharField(max_length=120)
    email = forms.EmailField(required=True)
    pic = forms.ImageField(label='Profile Picture', required=False)
    bio = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = User
        fields = ("username", "name", "email", "pic", "bio", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        # Customize help texts
        self.fields['username'].help_text = None
        self.fields['password1'].help_text = "Your password must contain at least 8 characters and can't be entirely numeric."
        

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .models import CustomUser
from recipes.models import Recipe
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from .forms import CustomUserCreationForm

# Create your views here.
class profile(LoginRequiredMixin, DetailView):
    model: CustomUser
    template_name = 'users/user_profile.html'
    context_object_name = 'current_user'

    def get_object(self, queryset=None):
        return CustomUser.objects.get(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Fetch recipes authored by the current user
        context['recipes'] = Recipe.objects.filter(author=self.object)
        return context

# function to create a user
def signup_view(request):
    error_message = None
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = None
            try:
                user = User.objects.create_user(
                    username=form.cleaned_data['username']
                )
                user.set_password(form.cleaned_data['password1'])
                user.save()

                pic = form.cleaned_data['pic']
                if not pic:
                    pic = 'no_picture.jpg'

                print(user)
                print(form.cleaned_data['password1'])
                customuser = CustomUser(
                    user=user,
                    name=form.cleaned_data['name'],
                    pic=pic,
                    description=form.cleaned_data['bio'],
                    email=form.cleaned_data['email'],
                )
                customuser.save()

                user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
                login(request, user)
                return redirect('users:profile')
            
            except Exception as e:
                print(e)
                if user:
                    user.delete()
                error_message = f'Something went wrong. Please try again'
        else:
            print(form.errors)
            error_message = 'Something went wrong.'
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
        'error_message': error_message
    }

    return render(request, 'auth/signup.html', context)

users/templates/users/user_profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
    <title>Recipes Home</title>
    <link rel="shortcut icon" href="{% static 'recipes/images/' %}">
    <style> 
        body {
            margin: 0;
            padding: 0;
            overflow-x: hidden; /* Prevent horizontal overflow */
        }

        .main-container {
            display: flex;
            flex-direction: column;
            background-color: #F6F5F2;
            padding: 20px;
            border-radius: 10px;
            width: 70%;
            margin-top: 50px;
            margin-left: 12%;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            box-sizing: border-box;
            position: relative;
        }

        .user-container-details {
            padding: 10px;
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            box-sizing: border-box;
        }

        .right {
            padding: 10px;
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            box-sizing: border-box;
        }

        .main-box {
            display: flex;
            align-items: center;
            flex-direction: column;
            width: 100%;
        }

        .main-box ul {
            padding: 0;
            list-style-type: none;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            margin: 0; /* Remove default margin */
            width: 100%; /* Full width of the parent container */
        }

        .main-box ul li {
            width: 100%;
            max-width: 300px;
            margin: 15px;
            border-radius: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            background: rgba(255, 255, 255, 0.3);
            transition: 0.25s ease-out;
            justify-content: center;
            align-items: center;
            display: flex;
            flex-direction: column; /* Stack content vertically */
            box-sizing: border-box;
            
        }

        .main-box ul li a {
            text-decoration: none;
        }

        .main-box ul li img {
            object-fit: cover;
            width: 300px;
            height: 300px;
        }

        @media all and (max-width: 550px) {
            .main-container {
                width: 100%;
                margin-left: 0;
                padding: 10px;
                box-sizing: border-box;
            }        

            .right {
                width: 100%;
                padding: 10px;
                box-sizing: border-box;
                position: static; /* Ensure normal flow */
            }

            .main-box {
                flex-direction: column;
                align-items: center;
            }

            .main-box ul {
                padding: 10px;
                flex-direction: column;
                align-items: center;
            }

            .main-box ul li {
                width: 100%;
            }

            .main-box ul li img {
                width: 100%;
            }
        }
    </style>
</head>
<body>
    <header class="page-header">
        <h1>Recipe App</h1>
        <nav class="main-navigation page-header__item">
            <ul role="menubar" class="navigation-list">
                <li role="presentation" role="menuitem" class="navigation-list__item"><a href="{% url 'recipes:create' %}">Create</a></li>
                <li role="presentation" role="menuitem" class="navigation-list__item"><a href="{% url 'recipes:list' %}">Recipes</a></li>
                <li role="presentation" role="menuitem" class="navigation-list__item"><a href="{% url 'users:profile' %}">Profile</a></li>
                <li role="presentation" role="menuitem" class="navigation-list__item"><a href ="{%url 'logout' %}"> Logout </a></li>
            </ul>
         </nav>
    </header>
    <div class="main-container">
        <div class="user-container-details">
            <h1>Welcome to your profile!</h1>
            <b>Author:</b> {{current_user.name}} <br>
            <b>Username: </b> {{current_user.user}} <br>
            <b>Description: </b> {{current_user.description}} <br>
            <div class="image-container">
                <img src="{{object.pic.url}}" class="detail-image"/>
            </div>
        </div>
        <hr>
        <div class="right">
            <h2>All Recipes By {{current_user.name}}</h2>
            <div class="main-box">
                {% if recipes %}
                    <ul>
                        {% for recipe in recipes %}
                        <li>
                            <a href="{% url 'recipes:detail' pk=recipe.id %}">
                                <h2>{{ recipe.name }}</h2>
                                <img src="{{ recipe.pic.url }}" />
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>You currently have no recipes yet!</p>
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>